name: EarthCoordinate
version: 1.0.0
main: net.mncraft.earthcoordinate.EarthCoordinate
author: Bilguun Ochirbat
commands:
  earthcoordinate:
    description: Convert real world coordinates to minecraft coordinates
    usage: /<command>
    aliases: [ecoordinate, ecoord, earthcoordinate, earthcoordinate]
permissions:
  earthcoordinate.*:
    description: Gives access to all commands
    children:
      earthcoordinate.basic: true
      earthcoordinate.reload: true
  earthcoordinate.convert.*:
    description: Allows player to convert coordinates
    default: true
    children:
      earthcoordinate.convert.earth2mc: true
      earthcoordinate.convert.mc2earth: true
  earthcoordinate.reload:
    description: Reloads plugin configuration
    default: op